#!//anaconda/envs/nbody6++vis/bin/python

import pandas as pd
import os

things = os.listdir('.')


if 'cluser_status.csv' not in things and 'cluster_status.csv' not in things:
    raise IOError('File cluser_status.csv [OLD] or cluster_status.csv not found in directory!, are you in an nbody simulation?')

if 'cluser_status.csv' in things:
    filename = 'cluser_status.csv'
elif 'cluster_status.csv' in things:
    filename = 'cluster_status.csv'

df = pd.read_csv(filename, sep=r'\s+', engine='python')
df['Time'] = df['TTOT']*df['TSTAR']
last_time = df['Time'].iloc[-1]
Physical_time = ("{:0.2f} Myr".format(last_time) if last_time < 1000 else "{:0.2f} Gyr".format(last_time/1000))
print('Total time elapsed: {}, {:0.2f} NB'.format(Physical_time, df['TTOT'].iloc[-1]))
