#!//anaconda/envs/nbody6++vis/bin/python

import pandas as pd
import os

things = os.listdir('.')


if 'cluser_status.csv' not in things and 'cluster_status.csv' not in things:
    raise IOError('File cluser_status.csv [OLD] or cluster_status.csv not found in directory!, are you in an nbody simulation?')

if 'cluser_status.csv' in things:
    filename = 'cluser_status.csv'
elif 'cluster_status.csv' in things:
    filename = 'cluster_status.csv'

df = pd.read_csv(filename, sep=r'\s+', engine='python')
df['Time'] = df['TTOT']*df['TSTAR']
print('Total time elapsed: {:0.2f} Myr'.format(df['Time'].iloc[-1]))
